//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var org_thriftee_examples_usergroup_domain_ttypes = require('./org_thriftee_examples_usergroup_domain_types')


var ttypes = require('./org_thriftee_examples_usergroup_service_types');
//HELPER FUNCTIONS AND STRUCTURES

GroupService_addUserToGroup_args = function(args) {
  this.arg0 = null;
  this.arg1 = null;
  if (args) {
    if (args.arg0 !== undefined) {
      this.arg0 = args.arg0;
    }
    if (args.arg1 !== undefined) {
      this.arg1 = args.arg1;
    }
  }
};
GroupService_addUserToGroup_args.prototype = {};
GroupService_addUserToGroup_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.arg0 = new org_thriftee_examples_usergroup_domain_ttypes.Group();
        this.arg0.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.arg1 = new org_thriftee_examples_usergroup_domain_ttypes.User();
        this.arg1.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GroupService_addUserToGroup_args.prototype.write = function(output) {
  output.writeStructBegin('GroupService_addUserToGroup_args');
  if (this.arg0 !== null && this.arg0 !== undefined) {
    output.writeFieldBegin('arg0', Thrift.Type.STRUCT, 1);
    this.arg0.write(output);
    output.writeFieldEnd();
  }
  if (this.arg1 !== null && this.arg1 !== undefined) {
    output.writeFieldBegin('arg1', Thrift.Type.STRUCT, 2);
    this.arg1.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GroupService_addUserToGroup_result = function(args) {
  this.success = null;
  this.ex1 = null;
  if (args instanceof ttypes.UserGroupException) {
    this.ex1 = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ex1 !== undefined) {
      this.ex1 = args.ex1;
    }
  }
};
GroupService_addUserToGroup_result.prototype = {};
GroupService_addUserToGroup_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex1 = new ttypes.UserGroupException();
        this.ex1.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GroupService_addUserToGroup_result.prototype.write = function(output) {
  output.writeStructBegin('GroupService_addUserToGroup_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.ex1 !== null && this.ex1 !== undefined) {
    output.writeFieldBegin('ex1', Thrift.Type.STRUCT, 1);
    this.ex1.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GroupService_find_args = function(args) {
  this.arg0 = null;
  if (args) {
    if (args.arg0 !== undefined) {
      this.arg0 = args.arg0;
    }
  }
};
GroupService_find_args.prototype = {};
GroupService_find_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.arg0 = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GroupService_find_args.prototype.write = function(output) {
  output.writeStructBegin('GroupService_find_args');
  if (this.arg0 !== null && this.arg0 !== undefined) {
    output.writeFieldBegin('arg0', Thrift.Type.STRING, 1);
    output.writeString(this.arg0);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GroupService_find_result = function(args) {
  this.success = null;
  this.ex1 = null;
  if (args instanceof ttypes.UserGroupException) {
    this.ex1 = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ex1 !== undefined) {
      this.ex1 = args.ex1;
    }
  }
};
GroupService_find_result.prototype = {};
GroupService_find_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new org_thriftee_examples_usergroup_domain_ttypes.Group();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex1 = new ttypes.UserGroupException();
        this.ex1.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GroupService_find_result.prototype.write = function(output) {
  output.writeStructBegin('GroupService_find_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ex1 !== null && this.ex1 !== undefined) {
    output.writeFieldBegin('ex1', Thrift.Type.STRUCT, 1);
    this.ex1.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GroupService_groupNames_args = function(args) {
  this.arg0 = null;
  if (args) {
    if (args.arg0 !== undefined) {
      this.arg0 = args.arg0;
    }
  }
};
GroupService_groupNames_args.prototype = {};
GroupService_groupNames_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.arg0 = new org_thriftee_examples_usergroup_domain_ttypes.User();
        this.arg0.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GroupService_groupNames_args.prototype.write = function(output) {
  output.writeStructBegin('GroupService_groupNames_args');
  if (this.arg0 !== null && this.arg0 !== undefined) {
    output.writeFieldBegin('arg0', Thrift.Type.STRUCT, 1);
    this.arg0.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GroupService_groupNames_result = function(args) {
  this.success = null;
  this.ex1 = null;
  if (args instanceof ttypes.UserGroupException) {
    this.ex1 = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ex1 !== undefined) {
      this.ex1 = args.ex1;
    }
  }
};
GroupService_groupNames_result.prototype = {};
GroupService_groupNames_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readString();
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex1 = new ttypes.UserGroupException();
        this.ex1.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GroupService_groupNames_result.prototype.write = function(output) {
  output.writeStructBegin('GroupService_groupNames_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRING, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        output.writeString(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.ex1 !== null && this.ex1 !== undefined) {
    output.writeFieldBegin('ex1', Thrift.Type.STRUCT, 1);
    this.ex1.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GroupServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
GroupServiceClient.prototype = {};
GroupServiceClient.prototype.seqid = function() { return this._seqid; }
GroupServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
GroupServiceClient.prototype.addUserToGroup = function(arg0, arg1, callback) {
  this._seqid = this.new_seqid();
  this._reqs[this.seqid()] = callback;
  this.send_addUserToGroup(arg0, arg1);
};

GroupServiceClient.prototype.send_addUserToGroup = function(arg0, arg1) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('addUserToGroup', Thrift.MessageType.CALL, this.seqid());
  var args = new GroupService_addUserToGroup_args();
  args.arg0 = arg0;
  args.arg1 = arg1;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GroupServiceClient.prototype.recv_addUserToGroup = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GroupService_addUserToGroup_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex1) {
    return callback(result.ex1);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('addUserToGroup failed: unknown result');
};
GroupServiceClient.prototype.find = function(arg0, callback) {
  this._seqid = this.new_seqid();
  this._reqs[this.seqid()] = callback;
  this.send_find(arg0);
};

GroupServiceClient.prototype.send_find = function(arg0) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('find', Thrift.MessageType.CALL, this.seqid());
  var args = new GroupService_find_args();
  args.arg0 = arg0;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GroupServiceClient.prototype.recv_find = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GroupService_find_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex1) {
    return callback(result.ex1);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('find failed: unknown result');
};
GroupServiceClient.prototype.groupNames = function(arg0, callback) {
  this._seqid = this.new_seqid();
  this._reqs[this.seqid()] = callback;
  this.send_groupNames(arg0);
};

GroupServiceClient.prototype.send_groupNames = function(arg0) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('groupNames', Thrift.MessageType.CALL, this.seqid());
  var args = new GroupService_groupNames_args();
  args.arg0 = arg0;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GroupServiceClient.prototype.recv_groupNames = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GroupService_groupNames_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex1) {
    return callback(result.ex1);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('groupNames failed: unknown result');
};
GroupServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
GroupServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

GroupServiceProcessor.prototype.process_addUserToGroup = function(seqid, input, output) {
  var args = new GroupService_addUserToGroup_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.addUserToGroup(args.arg0, args.arg1, function (err, result) {
    var result = new GroupService_addUserToGroup_result((err != null ? err : {success: result}));
    output.writeMessageBegin("addUserToGroup", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

GroupServiceProcessor.prototype.process_find = function(seqid, input, output) {
  var args = new GroupService_find_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.find(args.arg0, function (err, result) {
    var result = new GroupService_find_result((err != null ? err : {success: result}));
    output.writeMessageBegin("find", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

GroupServiceProcessor.prototype.process_groupNames = function(seqid, input, output) {
  var args = new GroupService_groupNames_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.groupNames(args.arg0, function (err, result) {
    var result = new GroupService_groupNames_result((err != null ? err : {success: result}));
    output.writeMessageBegin("groupNames", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

